---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: aws-concourse
  - name: pcfawsops-terraform-state-get
outputs:
  - name: pcfawsops-terraform-state-put
params:
  TF_VAR_aws_access_key:
  TF_VAR_aws_secret_key:
  TF_VAR_aws_key_name:
  TF_VAR_aws_cert_arn:
  TF_VAR_rds_db_username:
  TF_VAR_rds_db_password:
  TF_VAR_environment:
  TF_VAR_opsman_ami:
  TF_VAR_amis_nat:
  TF_VAR_aws_region:
  TF_VAR_az1:
  TF_VAR_az2:
  TF_VAR_az3:
  TF_VAR_route53_zone_id:
run:
  path: aws-concourse/scripts/prepare-aws.sh
